name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install pnpm
      - name: Install pnpm
        run: |
          curl -L https://get.pnpm.io | bash -s -- --global
        if: success() # Only run if the previous step was successful

      # Install dependencies
      - name: Install dependencies
        run: pnpm install
        if: success() # Only run if the previous step was successful

      # Run the build command using pnpm
      - name: Build
        run: pnpm run build
        working-directory: ./path/to/your/app  # Specify the path to your app if necessary
        if: success() # Only run if the previous step was successful

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENGREESI }}'
          channelId: live
          projectId: engreesi
